// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbzlhueozvnpjtqekuqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiemxodWVvenZucGp0cWVrdXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NDYwODksImV4cCI6MjA4ODEyMjA4OX0.VI5X3m8k-NZevwHCniM7qc_5VHuQJu7Zwb9GzU2AsIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});